[out:json][timeout:90];
(
  way["highway"]["name"~"^(Mahatma Gandhi Road|M G Road|MG Road|Residency Road|Lower Agaram Road|Agaram Road|Thimmaiah Road|Narayan Pillai Street|Narayanapillai Street|Narayana Pillai Street|Old Post Office Road|City Civil Court Road|Lavelle Road|Brigade Road|Raja Ram Mohan Roy Road|R R M R Road|Kamaraj Road|Commercial Street)$",i](12.93,77.58,13.00,77.64);
);
out geom tags;
